export const marineLocations = [
  {
    id: "vizag",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    sea: "Bay of Bengal",
    lat: 17.6868,
    lon: 83.2185,
    sst: 28.4,
    chlorophyll: 0.85,
    windSpeed: 14,
    windDirection: "ENE",
    windDegrees: 65,
    waveHeight: 1.6,
    wavePeriod: 7.8,
    swellHeight: 1.2,
    swellPeriod: 11.5,
    currentSpeed: 0.42,
    currentDirection: "NE",
    tideStatus: "Rising",
    nextHighTide: "08:42 AM (1.35m)",
    nextLowTide: "02:50 PM (0.28m)",
    riskScore: 28,
    riskLevel: "Low",
    weather: {
      condition: "Fair",
      temp: 29.2,
      humidity: 78,
      visibility: 12,
      pressure: 1011,
    },
  },
  {
    id: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    sea: "Bay of Bengal",
    lat: 13.0827,
    lon: 80.2707,
    sst: 29.1,
    chlorophyll: 0.92,
    windSpeed: 18,
    windDirection: "NE",
    windDegrees: 45,
    waveHeight: 2.1,
    wavePeriod: 8.4,
    swellHeight: 1.7,
    swellPeriod: 12.0,
    currentSpeed: 0.65,
    currentDirection: "NNE",
    tideStatus: "High",
    nextHighTide: "07:15 AM (1.20m)",
    nextLowTide: "01:30 PM (0.35m)",
    riskScore: 42,
    riskLevel: "Moderate",
    weather: {
      condition: "Cloudy",
      temp: 28.6,
      humidity: 82,
      visibility: 9,
      pressure: 1009,
    },
  },
  {
    id: "kochi",
    name: "Kochi",
    state: "Kerala",
    sea: "Arabian Sea",
    lat: 9.9312,
    lon: 76.2673,
    sst: 28.8,
    chlorophyll: 1.24,
    windSpeed: 11,
    windDirection: "WNW",
    windDegrees: 290,
    waveHeight: 1.3,
    wavePeriod: 6.9,
    swellHeight: 0.9,
    swellPeriod: 9.8,
    currentSpeed: 0.38,
    currentDirection: "SSE",
    tideStatus: "Falling",
    nextHighTide: "11:20 AM (0.95m)",
    nextLowTide: "05:10 PM (0.18m)",
    riskScore: 22,
    riskLevel: "Low",
    weather: {
      condition: "Light Rain",
      temp: 27.5,
      humidity: 88,
      visibility: 8,
      pressure: 1012,
    },
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    sea: "Arabian Sea",
    lat: 18.922,
    lon: 72.8347,
    sst: 27.9,
    chlorophyll: 0.74,
    windSpeed: 16,
    windDirection: "NW",
    windDegrees: 315,
    waveHeight: 1.8,
    wavePeriod: 7.2,
    swellHeight: 1.4,
    swellPeriod: 10.4,
    currentSpeed: 0.52,
    currentDirection: "S",
    tideStatus: "Rising",
    nextHighTide: "09:30 AM (3.80m)",
    nextLowTide: "03:45 PM (1.10m)",
    riskScore: 35,
    riskLevel: "Moderate",
    weather: {
      condition: "Fair",
      temp: 30.1,
      humidity: 71,
      visibility: 10,
      pressure: 1013,
    },
  },
  {
    id: "paradip",
    name: "Paradip",
    state: "Odisha",
    sea: "Bay of Bengal",
    lat: 20.3164,
    lon: 86.6114,
    sst: 27.8,
    chlorophyll: 1.45,
    windSpeed: 24,
    windDirection: "E",
    windDegrees: 90,
    waveHeight: 2.8,
    wavePeriod: 9.1,
    swellHeight: 2.3,
    swellPeriod: 13.2,
    currentSpeed: 0.85,
    currentDirection: "NE",
    tideStatus: "Falling",
    nextHighTide: "06:40 AM (2.10m)",
    nextLowTide: "01:05 PM (0.45m)",
    riskScore: 68,
    riskLevel: "Elevated",
    weather: {
      condition: "Squally",
      temp: 26.8,
      humidity: 92,
      visibility: 5,
      pressure: 1004,
    },
  },
  {
    id: "kanyakumari",
    name: "Kanyakumari",
    state: "Tamil Nadu",
    sea: "Indian Ocean",
    lat: 8.0883,
    lon: 77.5385,
    sst: 28.5,
    chlorophyll: 0.98,
    windSpeed: 21,
    windDirection: "ENE",
    windDegrees: 70,
    waveHeight: 2.4,
    wavePeriod: 8.8,
    swellHeight: 2.0,
    swellPeriod: 14.1,
    currentSpeed: 0.72,
    currentDirection: "W",
    tideStatus: "Low",
    nextHighTide: "10:15 AM (0.85m)",
    nextLowTide: "04:30 PM (0.12m)",
    riskScore: 54,
    riskLevel: "Moderate",
    weather: {
      condition: "Cloudy",
      temp: 28.0,
      humidity: 79,
      visibility: 11,
      pressure: 1010,
    },
  },
];

export const pfzZones = [
  {
    id: "pfz-vizag-01",
    name: "Bheemunipatnam Offshore Front (East Sector-A)",
    referencePort: "Visakhapatnam",
    lat: 17.892,
    lon: 83.584,
    distanceNM: 18.2,
    bearing: "ENE",
    bearingDeg: 68,
    depthMeters: 55,
    sstC: 27.9,
    sstGradientC: "0.8°C / 2km Front",
    chlorophyllMgM3: 1.15,
    suitabilityScore: 94,
    suitabilityText: "Very High",
    primarySpecies: ["Yellowfin Tuna", "Skipjack", "Indian Mackerel", "Sardines"],
    recommendedGear: "Gillnet / Hook & Line",
    advisoryValidity: "Next 36 Hours (INCOIS Confirmed)",
    fuelEstimatedLiters: 42,
    transitHours: 1.8,
  },
  {
    id: "pfz-vizag-02",
    name: "Kalingapatnam Shelf Boundary",
    referencePort: "Visakhapatnam",
    lat: 18.214,
    lon: 84.112,
    distanceNM: 44.5,
    bearing: "NE",
    bearingDeg: 42,
    depthMeters: 85,
    sstC: 28.1,
    sstGradientC: "0.6°C / 3km Front",
    chlorophyllMgM3: 0.92,
    suitabilityScore: 86,
    suitabilityText: "High",
    primarySpecies: ["Seer Fish (King Mackerel)", "Carangids", "Tuna"],
    recommendedGear: "Trolling / Longline",
    advisoryValidity: "Next 24 Hours",
    fuelEstimatedLiters: 98,
    transitHours: 4.2,
  },
  {
    id: "pfz-chennai-01",
    name: "Pulicat Shoal Chlorophyll Bloom",
    referencePort: "Chennai",
    lat: 13.412,
    lon: 80.481,
    distanceNM: 22.8,
    bearing: "NNE",
    bearingDeg: 28,
    depthMeters: 40,
    sstC: 28.6,
    sstGradientC: "0.9°C / 1.5km Front",
    chlorophyllMgM3: 1.38,
    suitabilityScore: 91,
    suitabilityText: "Very High",
    primarySpecies: ["Prawns / Shrimps", "Ribbonfish", "Pomfret", "Anchovy"],
    recommendedGear: "Trawl Net / Bottom Gillnet",
    advisoryValidity: "Next 48 Hours",
    fuelEstimatedLiters: 52,
    transitHours: 2.2,
  },
  {
    id: "pfz-kochi-01",
    name: "Wadge Bank Edge Upwelling",
    referencePort: "Kochi",
    lat: 9.612,
    lon: 75.814,
    distanceNM: 28.4,
    bearing: "WSW",
    bearingDeg: 245,
    depthMeters: 65,
    sstC: 27.5,
    sstGradientC: "1.2°C / 2km Upwelling",
    chlorophyllMgM3: 1.62,
    suitabilityScore: 96,
    suitabilityText: "Very High",
    primarySpecies: ["Indian Oil Sardine", "Mackerel", "Squid", "Snapper"],
    recommendedGear: "Ring Seine / Purse Seine",
    advisoryValidity: "Next 36 Hours",
    fuelEstimatedLiters: 65,
    transitHours: 2.6,
  },
  {
    id: "pfz-paradip-01",
    name: "Dhamra Estuarine Thermal Confluence",
    referencePort: "Paradip",
    lat: 20.651,
    lon: 87.124,
    distanceNM: 32.1,
    bearing: "ENE",
    bearingDeg: 62,
    depthMeters: 38,
    sstC: 27.2,
    sstGradientC: "1.0°C / 2km Front",
    chlorophyllMgM3: 1.84,
    suitabilityScore: 78,
    suitabilityText: "Moderate",
    primarySpecies: ["Hilsa", "Croakers", "Catfish", "Pomfret"],
    recommendedGear: "Drift Gillnet",
    advisoryValidity: "Caution: High Sea State",
    fuelEstimatedLiters: 74,
    transitHours: 3.1,
  },
];

export const marineAlerts = [
  {
    id: "alert-01",
    source: "Official IMD",
    type: "Strong Wind",
    severity: "Severe",
    title: "Gale Wind Warning along North Andhra & Odisha Coast",
    summary:
      "Squally wind speed reaching 45-55 kmph gusting to 65 kmph likely to prevail over Northwest Bay of Bengal.",
    affectedRegions: ["Visakhapatnam", "Kalingapatnam", "Gopalpur", "Paradip"],
    issuedAt: "Today, 06:00 IST",
    expiresAt: "Tomorrow, 18:00 IST",
    coordinates: { lat: 18.5, lon: 84.8 },
    operationalAction:
      "Fishermen are advised not to venture into deep sea waters of Northwest Bay of Bengal.",
  },
  {
    id: "alert-02",
    source: "Official INCOIS",
    type: "High Wave",
    severity: "Warning",
    title: "High Wave Alert (Swell Surge) for South Tamil Nadu Coast",
    summary:
      "High waves in the range of 2.2 - 2.8 meters are forecast till 23:30 hours along the coast from Kanyakumari to Rameswaram.",
    affectedRegions: ["Kanyakumari", "Tuticorin", "Rameswaram"],
    issuedAt: "Today, 08:30 IST",
    expiresAt: "Today, 23:30 IST",
    coordinates: { lat: 8.5, lon: 78.2 },
    operationalAction:
      "Small craft and country boats advised to anchor safely and avoid beach landings.",
  },
  {
    id: "alert-03",
    source: "SALTY AI Model",
    type: "Squall / Thunderstorm",
    severity: "Severe",
    title: "Predictive Radar Cluster: Rapid Convective Cell Formation",
    summary:
      "Satellite IR anomaly detects severe localized cumulonimbus development 35NM East of Chennai. Sudden wind shifts >35kts expected within 2 hours.",
    affectedRegions: ["Chennai Offshore", "Pulicat Sector"],
    issuedAt: "45 mins ago (Automated ML Pipeline)",
    expiresAt: "Next 4 hours",
    coordinates: { lat: 13.2, lon: 80.8 },
    operationalAction:
      "Boats operating within 30NM of Chennai advised to seek nearest harbor or navigate West.",
  },
  {
    id: "alert-04",
    source: "Official Coast Guard",
    type: "Cyclone",
    severity: "Advisory",
    title: "Depression BOB-04 Track Watch - Deep Central Bay",
    summary:
      "Well-marked low pressure area concentrated into depression BOB-04 over Central Bay of Bengal. Moving WNW at 14 kmph.",
    affectedRegions: ["Central Bay of Bengal", "North Andhra Coast"],
    issuedAt: "Yesterday, 18:00 IST",
    expiresAt: "Next 48 hours",
    coordinates: { lat: 15.2, lon: 86.4 },
    operationalAction:
      "All deep-sea fishing trawlers operating east of 85°E advised to return to coast immediately.",
  },
];

export const geofenceZones = [
  {
    id: "geo-imbl-srilanka",
    name: "India-Sri Lanka IMBL (Palk Strait & Gulf of Mannar)",
    category: "IMBL (International Boundary)",
    sea: "Palk Bay / Gulf of Mannar",
    status: "Strictly Prohibited",
    description:
      "International Maritime Boundary Line. Crossing into foreign territorial waters leads to immediate vessel impoundment and diplomatic arrest.",
    penaltyWarning: "Severe: Coast Guard & Sri Lankan Navy active radar cordon.",
    points: [
      { lat: 10.05, lon: 79.85 },
      { lat: 9.85, lon: 79.55 },
      { lat: 9.25, lon: 79.35 },
      { lat: 8.85, lon: 79.05 },
    ],
  },
  {
    id: "geo-mpa-gahirmatha",
    name: "Gahirmatha Marine Sanctuary (Olive Ridley Nesting Zone)",
    category: "Marine Protected Area",
    sea: "Bay of Bengal (Odisha)",
    status: "Restricted Fishing",
    description:
      "Strict ban on mechanized fishing and trawling within 20km from the coast from November to May to protect endangered Olive Ridley sea turtles.",
    penaltyWarning:
      "Forest Dept seizure of boat and fishing nets under Wildlife Protection Act.",
    points: [
      { lat: 20.8, lon: 86.9 },
      { lat: 20.8, lon: 87.2 },
      { lat: 20.4, lon: 87.1 },
      { lat: 20.4, lon: 86.8 },
    ],
  },
  {
    id: "geo-naval-vizag",
    name: "Eastern Naval Command Range (ENC Zulu-4)",
    category: "Naval Restricted Zone",
    sea: "Bay of Bengal",
    status: "Strictly Prohibited",
    description:
      "Subsurface and surface naval gunnery practice zone 15NM south of Dolphin's Nose.",
    penaltyWarning: "Hazardous live firing exercises active on scheduled NOTAMs.",
    points: [
      { lat: 17.5, lon: 83.3 },
      { lat: 17.5, lon: 83.6 },
      { lat: 17.2, lon: 83.6 },
      { lat: 17.2, lon: 83.3 },
    ],
  },
  {
    id: "geo-gulf-mannar-bio",
    name: "Gulf of Mannar Coral Biosphere Reserve",
    category: "Marine Protected Area",
    sea: "Gulf of Mannar",
    status: "Restricted Fishing",
    description:
      "Coral reef conservation park across 21 islands. Trawling and destructive blast fishing banned.",
    penaltyWarning: "Violations subject to heavy environmental fines.",
    points: [
      { lat: 9.2, lon: 78.8 },
      { lat: 9.2, lon: 79.2 },
      { lat: 8.7, lon: 78.7 },
      { lat: 8.7, lon: 78.3 },
    ],
  },
];

export const activeVessels = [
  {
    id: "vessel-01",
    name: "Matsya-Kuber IV",
    regNumber: "IND-AP-02-MM-4912",
    vesselType: "Mechanized Trawler (48ft)",
    ownerName: "Ramu K. / Vizag Trawler Union",
    homePort: "Visakhapatnam",
    mmsi: "419001892",
    currentLat: 17.742,
    currentLon: 83.485,
    sogKnots: 7.4,
    cogDegrees: 72,
    headingText: "ENE",
    fuelRemainingLiters: 380,
    fuelCapacityLiters: 600,
    engineRpm: 1650,
    tripDurationHours: 14.5,
    distanceFromPortNM: 16.4,
    distanceToIMBLNM: 142.0,
    geofenceStatus: "SAFE",
    riskRating: "Low",
    crewCount: 6,
    lastPingTime: "Just now (AIS Class B)",
    sosActive: false,
  },
  {
    id: "vessel-02",
    name: "Samudra-Shakti II",
    regNumber: "IND-TN-07-MM-8120",
    vesselType: "Deep-Sea Longliner (65ft)",
    ownerName: "J. Fernandez",
    homePort: "Chennai",
    mmsi: "419002941",
    currentLat: 12.89,
    currentLon: 80.45,
    sogKnots: 8.2,
    cogDegrees: 110,
    headingText: "ESE",
    fuelRemainingLiters: 710,
    fuelCapacityLiters: 1200,
    engineRpm: 1800,
    tripDurationHours: 28.0,
    distanceFromPortNM: 24.1,
    distanceToIMBLNM: 68.5,
    geofenceStatus: "SAFE",
    riskRating: "Moderate",
    crewCount: 8,
    lastPingTime: "2 mins ago",
    sosActive: false,
  },
  {
    id: "vessel-03",
    name: "Velankanni Matha",
    regNumber: "IND-TN-11-MO-3012",
    vesselType: "Motorized Craft (32ft)",
    ownerName: "Anthony Raj",
    homePort: "Rameswaram",
    mmsi: "419009812",
    currentLat: 9.38,
    currentLon: 79.42,
    sogKnots: 5.1,
    cogDegrees: 95,
    headingText: "E",
    fuelRemainingLiters: 85,
    fuelCapacityLiters: 200,
    engineRpm: 1400,
    tripDurationHours: 8.2,
    distanceFromPortNM: 11.2,
    distanceToIMBLNM: 4.8,
    geofenceStatus: "CAUTION",
    riskRating: "Moderate",
    crewCount: 4,
    lastPingTime: "1 min ago",
    sosActive: false,
  },
  {
    id: "vessel-04",
    name: "ICGS Varuna (Patrol)",
    regNumber: "ICG-CG-71",
    vesselType: "Patrol Craft (ICG)",
    ownerName: "Indian Coast Guard District 6",
    homePort: "Visakhapatnam",
    mmsi: "419000071",
    currentLat: 17.62,
    currentLon: 83.35,
    sogKnots: 18.5,
    cogDegrees: 45,
    headingText: "NE",
    fuelRemainingLiters: 4200,
    fuelCapacityLiters: 8000,
    engineRpm: 2100,
    tripDurationHours: 4.0,
    distanceFromPortNM: 8.9,
    distanceToIMBLNM: 138.0,
    geofenceStatus: "SAFE",
    riskRating: "Low",
    crewCount: 22,
    lastPingTime: "Just now",
    sosActive: false,
  },
];

export const researchDatasets = [
  {
    id: "ds-sst-insat",
    name: "High-Resolution Satellite SST (INSAT-3DR)",
    instrument: "Imager / Sounder",
    sourceServer: "ERDDAP: incois.gov.in/erddap/griddap/insat_sst_hourly",
    temporalRange: "2018 - Present (Hourly)",
    resolution: "0.04° (~4 km)",
    parameters: ["sea_surface_temperature", "sst_anomaly", "quality_flags"],
    recordsCount: "1.4B grid points",
    format: ["NetCDF-4", "CSV", "GeoJSON", "OPeNDAP"],
    description:
      "Thermal infrared multichannel radiometer SST across North Indian Ocean with cloud filtering and in-situ buoy calibration.",
  },
  {
    id: "ds-chla-modis",
    name: "Ocean Color & Chlorophyll-a (MODIS Aqua)",
    instrument: "MODIS Spectroradiometer",
    sourceServer: "ERDDAP: oceanwatch.pifsc.noaa.gov/modis_chla_8day",
    temporalRange: "2002 - Present (8-day composite)",
    resolution: "1 km coastal / 4 km offshore",
    parameters: ["chlor_a", "par_radiation", "turbidity_kd490"],
    recordsCount: "680M grid points",
    format: ["NetCDF", "CSV", "GeoTIFF"],
    description:
      "Phytoplankton biomass indicator computed via OC3M algorithm. Essential for marine primary productivity and PFZ validation.",
  },
  {
    id: "ds-buoy-incois",
    name: "Moored Ocean Buoy Array (OON / INCOIS)",
    instrument: "CTD, ADCP, Anemometer",
    sourceServer: "ERDDAP: incois.gov.in/erddap/tabledap/moored_buoys",
    temporalRange: "1997 - Present (10-min timeseries)",
    resolution: "Point in-situ (18 buoy stations)",
    parameters: [
      "wave_height_swh",
      "wave_period",
      "wind_speed",
      "air_pressure",
      "sst_depth_1m",
      "salinity",
    ],
    recordsCount: "42M records",
    format: ["CSV", "JSON", "NetCDF"],
    description:
      "Deep sea and coastal oceanographic moored buoys across Bay of Bengal (BD series) and Arabian Sea (AD series).",
  },
  {
    id: "ds-argo-profiles",
    name: "Argo Float Subsurface Hydrography",
    instrument: "Profiling CTD Floats (0 - 2000m)",
    sourceServer: "ERDDAP: ifremer.fr/erddap/tabledap/ArgoFloats_IndianOcean",
    temporalRange: "2005 - Present (10-day cycles)",
    resolution: "Vertical 2000m profiles",
    parameters: [
      "temperature",
      "salinity",
      "pressure",
      "mixed_layer_depth",
      "dissolved_oxygen",
    ],
    recordsCount: "128,000 vertical profiles",
    format: ["NetCDF", "CSV"],
    description:
      "Autonomous profiling floats measuring North Indian Ocean heat content, halocline structure, and ocean barrier layers.",
  },
];

export const locationMarketData = {
  vizag: {
    locationId: "vizag",
    harbourName: "Visakhapatnam Fishing Harbour",
    topSpecies: "Yellowfin Tuna (Surai)",
    topSpeciesScientific: "Thunnus albacares",
    demandLevel: "High Demand (Top Traded)",
    landingVolumeText: "4.8 MT landed today",
    clearanceRate: "94%",
    benchmarkPrice: 420,
    benchmarkSpecies: "Yellowfin Tuna",
    priceChangeText: "+₹45 (+12%)",
    priceTrendPositive: true,
    marketStatus: "APMC Daily Auction Active",
    priceUpdateNote: "Export demand surge",
    auctionTime: "05:00 - 11:30 IST",
    items: [
      {
        species: "Yellowfin Tuna",
        localName: "Surai",
        pricePerKg: 420,
        priceChange24h: 45,
        priceChangePercent: 12.0,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 4.8,
      },
      {
        species: "Seer Fish (King Mackerel)",
        localName: "Vanjaram",
        pricePerKg: 650,
        priceChange24h: 50,
        priceChangePercent: 8.3,
        trend: "up",
        demandLevel: "High",
        landingTons: 2.1,
      },
      {
        species: "Indian Mackerel",
        localName: "Kanagurtalu",
        pricePerKg: 180,
        priceChange24h: -10,
        priceChangePercent: -5.2,
        trend: "down",
        demandLevel: "Moderate",
        landingTons: 6.4,
      },
      {
        species: "White Pomfret",
        localName: "Tella Chanduva",
        pricePerKg: 720,
        priceChange24h: 40,
        priceChangePercent: 5.8,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.2,
      },
      {
        species: "Oil Sardines",
        localName: "Kavallu",
        pricePerKg: 110,
        priceChange24h: 0,
        priceChangePercent: 0,
        trend: "stable",
        demandLevel: "Moderate",
        landingTons: 5.0,
      },
    ],
  },
  chennai: {
    locationId: "chennai",
    harbourName: "Kasimedu Fishing Harbour",
    topSpecies: "White Pomfret (Vellai Vaval)",
    topSpeciesScientific: "Pampus argenteus",
    demandLevel: "Peak Auction Demand",
    landingVolumeText: "5.4 MT landed today",
    clearanceRate: "96%",
    benchmarkPrice: 780,
    benchmarkSpecies: "White Pomfret",
    priceChangeText: "+₹60 (+8.3%)",
    priceTrendPositive: true,
    marketStatus: "Kasimedu Wholesale Wharf",
    priceUpdateNote: "High retail buying",
    auctionTime: "04:30 - 10:00 IST",
    items: [
      {
        species: "White Pomfret",
        localName: "Vellai Vaval",
        pricePerKg: 780,
        priceChange24h: 60,
        priceChangePercent: 8.3,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 1.8,
      },
      {
        species: "Tiger Prawns",
        localName: "Kara Eral",
        pricePerKg: 580,
        priceChange24h: 70,
        priceChangePercent: 13.7,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 3.2,
      },
      {
        species: "Seer Fish",
        localName: "Vanjaram",
        pricePerKg: 720,
        priceChange24h: 40,
        priceChangePercent: 5.9,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.5,
      },
      {
        species: "Ribbonfish",
        localName: "Savalai",
        pricePerKg: 140,
        priceChange24h: 0,
        priceChangePercent: 0,
        trend: "stable",
        demandLevel: "Moderate",
        landingTons: 4.1,
      },
      {
        species: "Barracuda",
        localName: "Sheela",
        pricePerKg: 310,
        priceChange24h: 15,
        priceChangePercent: 5.1,
        trend: "up",
        demandLevel: "Moderate",
        landingTons: 2.0,
      },
    ],
  },
  kochi: {
    locationId: "kochi",
    harbourName: "Cochin Fisheries Harbour (Thoppumpady)",
    topSpecies: "Indian Oil Sardine (Mathi)",
    topSpeciesScientific: "Sardinella longiceps",
    demandLevel: "Heavy Supply Clearance",
    landingVolumeText: "8.2 MT landed today",
    clearanceRate: "91%",
    benchmarkPrice: 140,
    benchmarkSpecies: "Oil Sardine",
    priceChangeText: "-₹15 (-9.7%)",
    priceTrendPositive: false,
    marketStatus: "Thoppumpady Morning Bidding",
    priceUpdateNote: "Abundant boat arrivals",
    auctionTime: "05:30 - 12:00 IST",
    items: [
      {
        species: "Indian Oil Sardine",
        localName: "Mathi / Chaala",
        pricePerKg: 140,
        priceChange24h: -15,
        priceChangePercent: -9.7,
        trend: "down",
        demandLevel: "High",
        landingTons: 8.2,
      },
      {
        species: "Karimeen (Pearl Spot)",
        localName: "Karimeen",
        pricePerKg: 540,
        priceChange24h: 30,
        priceChangePercent: 5.9,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 1.1,
      },
      {
        species: "Squid / Cuttlefish",
        localName: "Koonthal",
        pricePerKg: 320,
        priceChange24h: 20,
        priceChangePercent: 6.7,
        trend: "up",
        demandLevel: "High",
        landingTons: 2.9,
      },
      {
        species: "Indian Mackerel",
        localName: "Ayala",
        pricePerKg: 210,
        priceChange24h: -10,
        priceChangePercent: -4.5,
        trend: "down",
        demandLevel: "Moderate",
        landingTons: 4.3,
      },
      {
        species: "Yellowfin Tuna",
        localName: "Kera",
        pricePerKg: 380,
        priceChange24h: 25,
        priceChangePercent: 7.0,
        trend: "up",
        demandLevel: "Moderate",
        landingTons: 1.9,
      },
    ],
  },
  mumbai: {
    locationId: "mumbai",
    harbourName: "Sassoon Docks & Bhaucha Dhakka",
    topSpecies: "Silver Pomfret (Paplet)",
    topSpeciesScientific: "Pampus argenteus",
    demandLevel: "Highest Value Traded",
    landingVolumeText: "6.1 MT landed today",
    clearanceRate: "95%",
    benchmarkPrice: 850,
    benchmarkSpecies: "Silver Pomfret",
    priceChangeText: "+₹70 (+9.0%)",
    priceTrendPositive: true,
    marketStatus: "Sassoon Dock APMC Block",
    priceUpdateNote: "Metropolitan premium demand",
    auctionTime: "04:00 - 10:30 IST",
    items: [
      {
        species: "Silver Pomfret",
        localName: "Paplet",
        pricePerKg: 850,
        priceChange24h: 70,
        priceChangePercent: 9.0,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 2.2,
      },
      {
        species: "Bombay Duck",
        localName: "Bombil",
        pricePerKg: 160,
        priceChange24h: 20,
        priceChangePercent: 14.3,
        trend: "up",
        demandLevel: "High",
        landingTons: 5.5,
      },
      {
        species: "King Mackerel",
        localName: "Surmai",
        pricePerKg: 740,
        priceChange24h: 35,
        priceChangePercent: 5.0,
        trend: "up",
        demandLevel: "High",
        landingTons: 2.4,
      },
      {
        species: "Tiger Prawns",
        localName: "Kolambi",
        pricePerKg: 620,
        priceChange24h: 40,
        priceChangePercent: 6.9,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 3.1,
      },
      {
        species: "Indian Salmon",
        localName: "Rawas",
        pricePerKg: 890,
        priceChange24h: 50,
        priceChangePercent: 6.0,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.0,
      },
    ],
  },
  paradip: {
    locationId: "paradip",
    harbourName: "Paradip Major Fishing Harbour",
    topSpecies: "Hilsa / Ilish (Ilishi)",
    topSpeciesScientific: "Tenualosa ilisha",
    demandLevel: "Severe Scarcity Demand",
    landingVolumeText: "3.6 MT landed today",
    clearanceRate: "98%",
    benchmarkPrice: 920,
    benchmarkSpecies: "Hilsa (Ilish)",
    priceChangeText: "+₹110 (+13.6%)",
    priceTrendPositive: true,
    marketStatus: "Paradip Auction Shed",
    priceUpdateNote: "High export demand spike",
    auctionTime: "05:00 - 11:00 IST",
    items: [
      {
        species: "Hilsa (Ilish)",
        localName: "Ilishi",
        pricePerKg: 920,
        priceChange24h: 110,
        priceChangePercent: 13.6,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 1.4,
      },
      {
        species: "Croakers",
        localName: "Poha / Croaker",
        pricePerKg: 240,
        priceChange24h: 15,
        priceChangePercent: 6.7,
        trend: "up",
        demandLevel: "Moderate",
        landingTons: 3.2,
      },
      {
        species: "Black Pomfret",
        localName: "Kala Chandi",
        pricePerKg: 560,
        priceChange24h: 30,
        priceChangePercent: 5.7,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.8,
      },
      {
        species: "Tiger Shrimp",
        localName: "Bagda Chingri",
        pricePerKg: 520,
        priceChange24h: 40,
        priceChangePercent: 8.3,
        trend: "up",
        demandLevel: "Very High",
        landingTons: 2.1,
      },
      {
        species: "Sea Bass / Bhetki",
        localName: "Bhetki",
        pricePerKg: 680,
        priceChange24h: 45,
        priceChangePercent: 7.1,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.1,
      },
    ],
  },
  kanyakumari: {
    locationId: "kanyakumari",
    harbourName: "Chinnamuttam Fishing Harbour",
    topSpecies: "Yellowfin Tuna & Seer Fish",
    topSpeciesScientific: "Thunnus albacares",
    demandLevel: "High Export Interest",
    landingVolumeText: "4.1 MT landed today",
    clearanceRate: "93%",
    benchmarkPrice: 460,
    benchmarkSpecies: "Yellowfin Tuna",
    priceChangeText: "+₹35 (+8.2%)",
    priceTrendPositive: true,
    marketStatus: "Chinnamuttam Auction Shed",
    priceUpdateNote: "Firm aggregator buying",
    auctionTime: "05:00 - 11:30 IST",
    items: [
      {
        species: "Yellowfin Tuna",
        localName: "Soorai",
        pricePerKg: 460,
        priceChange24h: 35,
        priceChangePercent: 8.2,
        trend: "up",
        demandLevel: "High",
        landingTons: 2.8,
      },
      {
        species: "Seer Fish",
        localName: "Neimeen",
        pricePerKg: 640,
        priceChange24h: 40,
        priceChangePercent: 6.7,
        trend: "up",
        demandLevel: "High",
        landingTons: 1.6,
      },
      {
        species: "Reef Snapper",
        localName: "Sankara",
        pricePerKg: 340,
        priceChange24h: 10,
        priceChangePercent: 3.0,
        trend: "up",
        demandLevel: "Moderate",
        landingTons: 2.2,
      },
      {
        species: "Skipjack Tuna",
        localName: "Choora",
        pricePerKg: 280,
        priceChange24h: -15,
        priceChangePercent: -5.1,
        trend: "down",
        demandLevel: "Moderate",
        landingTons: 3.0,
      },
      {
        species: "Trevally / Caranx",
        localName: "Parai",
        pricePerKg: 360,
        priceChange24h: 20,
        priceChangePercent: 5.9,
        trend: "up",
        demandLevel: "Moderate",
        landingTons: 1.7,
      },
    ],
  },
};

export const fishSchoolUpdates = {
  vizag: {
    locationId: "vizag",
    zoneId: "pfz-vizag-01",
    zoneName: "Bheemunipatnam Offshore Front",
    zoneSector: "Sector-A (East)",
    distanceBearing: "18.2 NM • 068° ENE",
    distanceNM: 18.2,
    bearing: "ENE",
    biomassSurge: "+38%",
    surgePercentage: 38,
    growthRateText: "Rapid Aggregation Surge",
    schoolType: "Yellowfin & Skipjack Pods",
    targetSpecies: ["Yellowfin Tuna", "Skipjack", "Indian Mackerel"],
    depthRange: "20 - 55m",
    estimatedBiomassMT: "16.5 MT",
    schoolAlert:
      "Dense Skipjack and Yellowfin schools rapidly clustering along 0.8°C thermal front 18 NM ENE. High feeding activity detected.",
    environmentalTrigger:
      "0.8°C / 2km SST confluence front with 1.15 mg/m³ chlorophyll bloom",
    recommendedGear: "Gillnet / Hook & Line",
    lastUpdated: "20 mins ago (INCOIS Telemetry)",
  },
  chennai: {
    locationId: "chennai",
    zoneId: "pfz-chennai-01",
    zoneName: "Pulicat Shoal Chlorophyll Bloom",
    zoneSector: "Pulicat Deep Sector",
    distanceBearing: "22.8 NM • 028° NNE",
    distanceNM: 22.8,
    bearing: "NNE",
    biomassSurge: "+45%",
    surgePercentage: 45,
    growthRateText: "Massive School Influx",
    schoolType: "Prawn & Ribbonfish Shoal",
    targetSpecies: ["Tiger Prawns", "Ribbonfish", "Pomfret"],
    depthRange: "15 - 40m",
    estimatedBiomassMT: "21.0 MT",
    schoolAlert:
      "Rapid chlorophyll plume spike (1.38 mg/m³) triggering explosive juvenile prawn and ribbonfish aggregation 22 NM NNE.",
    environmentalTrigger: "0.9°C thermal boundary & Sentinel-3 OLCI chlorophyll bloom",
    recommendedGear: "Trawl Net / Bottom Gillnet",
    lastUpdated: "35 mins ago (Sentinel-3 OLCI)",
  },
  kochi: {
    locationId: "kochi",
    zoneId: "pfz-kochi-01",
    zoneName: "Wadge Bank Edge Upwelling",
    zoneSector: "Southwest Wadge Bank",
    distanceBearing: "28.4 NM • 245° WSW",
    distanceNM: 28.4,
    bearing: "WSW",
    biomassSurge: "+52%",
    surgePercentage: 52,
    growthRateText: "Upwelling Surge Multiplier",
    schoolType: "Oil Sardine & Mackerel Shoals",
    targetSpecies: ["Indian Oil Sardine", "Mackerel", "Squid"],
    depthRange: "25 - 65m",
    estimatedBiomassMT: "32.0 MT",
    schoolAlert:
      "1.2°C coastal upwelling front driving explosive baitfish clustering; rapid multi-kilometer school expansion underway.",
    environmentalTrigger:
      "1.2°C / 2km Upwelling front with 1.62 mg/m³ chlorophyll saturation",
    recommendedGear: "Ring Seine / Purse Seine",
    lastUpdated: "15 mins ago (Moored Buoy AD02)",
  },
  mumbai: {
    locationId: "mumbai",
    zoneId: "pfz-mumbai-01",
    zoneName: "Bombay High Shelf Edge",
    zoneSector: "Northwest Offshore Trench",
    distanceBearing: "34.0 NM • 285° WNW",
    distanceNM: 34.0,
    bearing: "WNW",
    biomassSurge: "+31%",
    surgePercentage: 31,
    growthRateText: "Shelf Aggregation Surge",
    schoolType: "King Mackerel & Carangid School",
    targetSpecies: ["King Mackerel", "Carangids", "Pomfret"],
    depthRange: "40 - 75m",
    estimatedBiomassMT: "19.5 MT",
    schoolAlert:
      "Thermal gradient edge at 45m shelf break causing rapid schooling of pelagic predator fish and bait shoals.",
    environmentalTrigger: "0.7°C thermal front at outer continental shelf break",
    recommendedGear: "Trolling / Longline / Gillnet",
    lastUpdated: "40 mins ago (Satellite Radiometry)",
  },
  paradip: {
    locationId: "paradip",
    zoneId: "pfz-paradip-01",
    zoneName: "Dhamra Estuarine Thermal Confluence",
    zoneSector: "Mouth of Dhamra River Plume",
    distanceBearing: "32.1 NM • 062° ENE",
    distanceNM: 32.1,
    bearing: "ENE",
    biomassSurge: "+41%",
    surgePercentage: 41,
    growthRateText: "Estuarine Plume Run",
    schoolType: "Hilsa & Estuarine Croaker Run",
    targetSpecies: ["Hilsa", "Croakers", "Catfish", "Pomfret"],
    depthRange: "15 - 38m",
    estimatedBiomassMT: "18.2 MT",
    schoolAlert:
      "Freshwater discharge confluence creating sudden rapid schooling of upstream migrating Hilsa.",
    environmentalTrigger: "1.0°C / 2km Front with 1.84 mg/m³ high nutrient plume",
    recommendedGear: "Drift Gillnet",
    lastUpdated: "25 mins ago (MODIS Chl-a)",
  },
  kanyakumari: {
    locationId: "kanyakumari",
    zoneId: "pfz-kanyakumari-01",
    zoneName: "Tri-Sea Convergence Front",
    zoneSector: "Cape Comorin Deep Shelf",
    distanceBearing: "19.5 NM • 155° SSE",
    distanceNM: 19.5,
    bearing: "SSE",
    biomassSurge: "+36%",
    surgePercentage: 36,
    growthRateText: "Convergence Surge",
    schoolType: "Deep-Sea Tuna & Trevally Pods",
    targetSpecies: ["Yellowfin Tuna", "Seer Fish", "Skipjack"],
    depthRange: "30 - 70m",
    estimatedBiomassMT: "15.0 MT",
    schoolAlert:
      "Tri-sea current confluence generating dynamic eddies; rapid schooling of tuna and skipjack pods verified.",
    environmentalTrigger:
      "Three-current confluence front with 1.12 mg/m³ chlorophyll boundary",
    recommendedGear: "Hook & Line / Deep-Sea Longline",
    lastUpdated: "30 mins ago (OON Buoy BD08)",
  },
};

export function getLocationMarketProfile(locationIdOrName) {
  const key = locationIdOrName.toLowerCase();
  if (locationMarketData[key]) return locationMarketData[key];
  const found = Object.values(locationMarketData).find(
    (m) => m.harbourName.toLowerCase().includes(key) || key.includes(m.locationId)
  );
  return found || locationMarketData.vizag;
}

export function getFishSchoolUpdate(locationIdOrName) {
  const key = locationIdOrName.toLowerCase();
  if (fishSchoolUpdates[key]) return fishSchoolUpdates[key];
  const found = Object.values(fishSchoolUpdates).find(
    (s) => s.locationId.includes(key) || key.includes(s.locationId)
  );
  return found || fishSchoolUpdates.vizag;
}
